version: 2
updates:

  # 1) TOP-LEVEL AGGREGATOR
  #    Scans the root POM, but ignores any dependencies physically declared in
  #    testing/**, dataset-acceptance-test/**, etc.
  - package-ecosystem: "maven"
    directory: "/provider/datset-azure"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    labels:
      - "dependencies"
      - "azure"         
    groups:
        azure-dependencies:
            patterns:
                - "*"
            update-types:
              - "major"
              - "minor"
              - "patch"
