
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    labels:
      - "dependencies"
      - "common"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "maven"
    directory: "/dataset-core-plus"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch","version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: "maven"
    directory: "/provider/dataset-aws"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch","version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: "maven"
    directory: "/provider/dataset-gc"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch","version-update:semver-minor", "version-update:semver-major"]