variables:
  AWS_BUILD_SUBDIR: provider/dataset-aws/build-aws
  AWS_TEST_SUBDIR: testing/dataset-test-aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: dataset
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: HELM
  AWS_EKS_DEPLOYMENT_NAME: os-dataset

  IBM_BUILD_SUBDIR: provider/dataset-ibm
  IBM_INT_TEST_SUBDIR: testing/dataset-test-ibm

  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-dataset-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-dataset-deploy

  #Azure
  AZURE_SERVICE: dataset
  AZURE_BUILD_SUBDIR: provider/dataset-azure
  AZURE_TEST_SUBDIR: testing/dataset-test-azure
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"

  - local: "devops/gc/pipeline/override-stages.yml"

# disable the eslint scanner
# I think this is being generated from the presence of an HTML file, but there
# is no javascript to scan, so the job isn't helpful and just gets in the way
eslint-sast:
  rules:
    - when: never
