variables:
  AZURE_SERVICE: dataset
  AZURE_BUILD_SUBDIR: provider/dataset-azure
  AZURE_TEST_SUBDIR: testing/dataset-test-azure

stages:
  - build
  - containerize
  - deploy

include:
  - project: "togp-boot/osdu-devops/epam-osdu-infra-automation"
    file: "pipelines/get-vault-secrets.yaml"
  - project: "togp-boot/osdu-devops/epam-osdu-infra-automation"
    file: "pipelines/build/maven-azure.gitlab-ci.yml"
  # Comment at first to only run build image.
  - project: "togp-boot/osdu-devops/epam-osdu-infra-automation"
    file: "pipelines/azure-containerize-java.gitlab-ci.yml"
  - project: "togp-boot/osdu-devops/epam-osdu-infra-automation"
    file: "pipelines/azure-aks-deploy.gitlab-ci.yml"
