# Service Config
image: __CONTAINER__
imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  apiPath: /api/dataset/v1/
  readinessProbeHttpPath: /api/dataset/v1/actuator/health
  livenessProbeHttpPath: /api/dataset/v1/actuator/health

serviceParameters:
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis/redisauthtoken"
  objectType: "secretsmanager"
  objectAlias: "CACHE_CLUSTER_KEY"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point"
  objectType: "ssmparameter"
  objectAlias: "CACHE_CLUSTER_ENDPOINT"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/redis-core/end-point-port"
  objectType: "ssmparameter"
  objectAlias: "CACHE_CLUSTER_PORT"
- objectName: "/osdu/{{ .Values.global.resourcePrefix }}/primary-region"
  objectType: "ssmparameter"
  objectAlias: primary-region
environmentVariables:
  - name: APPLICATION_PORT
    value: "8080"
  - name: AWS_REGION
    value: "{{ .Values.global.region }}"
  - name: ENVIRONMENT
    value: "{{ .Values.global.resourcePrefix }}"
  - name: JAVA_OPTS
    value: "-Xms538M -Xmx900M"
  - name: LOG_LEVEL
    value: "{{ .Values.global.logLevel }}"
  - name: SSM_ENABLED
    value: "True"
  - name: SSL_ENABLED
    value: "false"
  - name: ENTITLEMENTS_BASE_URL
    value: "http://os-entitlements:8080"
  - name: PARTITION_BASE_URL
    value: "http://os-partition:8080"
  - name: STORAGE_BASE_URL
    value: "http://os-storage:8080"
  - name: SCHEMA_BASE_URL
    value: "http://os-schema:8080"
  - name: PARAMETER_MOUNT_PATH
    value: "/mnt/params"
podAnnotations: {}

# Resource Config
replicaCount: 1
resources:
  limits:
    memory: 900M
  requests:
    cpu: 500m
    memory: 900M
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Security Config
serviceAccountRole: arn:aws:iam::{{ .Values.global.accountID }}:role/osdu-{{ .Values.global.resourcePrefix }}-{{ include "common.name" . }}
cors:
  maxAge: "60m"
  allowCredentials: true
  allowMethods: 
    - POST
    - GET
    - PUT
  allowHeaders:
    - Authorization
    - Data-Partition-Id
    - Correlation-Id
    - Content-Type
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
allowedPrincipals:
  - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
  - cluster.local/ns/{{ .Values.global.namespace }}/sa/os-file
  - cluster.local/ns/os-timeseries-dms/sa/os-timeseries-dms
  - cluster.local/ns/aws-binary-dms/sa/binary-dms
  - cluster.local/ns/osdu-airflow/sa/airflow-dag-upload
  - cluster.local/ns/osdu-airflow/sa/airflow-worker
  - cluster.local/ns/osdu-ingest/sa/os-data-workflow
  - cluster.local/ns/osdu-ingest/sa/os-ingestion-workflow
  - cluster.local/ns/osdu-seismic-ddms/sa/os-seismic-store
  - cluster.local/ns/osdu-well-delivery/sa/os-welldelivery
  - cluster.local/ns/osdu-wellbore-ddms/sa/os-wellbore-ddms
