# Default values for dataset-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false
  limitsEnabled: true
  logLevel: "ERROR"
  tier: ""
  autoscaling: true

data:
  # Configmap
  logLevel: ""
  # Deployment
  requestsCpu: "5m"
  requestsMemory: "300Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "dataset"
  imagePullPolicy: "IfNotPresent"
  image: ""
  # redis connection. Change it if you want to use external redis
  redisDatasetHost: ""
  redisDatasetPort: 6379
  redisImage: "docker.io/library/redis:7.2-alpine"

conf:
  configmap: "dataset-config"
  postgresSecretName: "dataset-postgres-secret"
  appName: "dataset"
  datasetRedisSecretName: "dataset-redis-secret"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "200m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "256Mi"
  sidecarInject: true

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue"
  targetValue: 136 #80*0.85*2
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 80
  tokensPerFill: 80
  fillInterval: "1s"
