# Default values for dataset-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  # Configmap
  logLevel: "ERROR"
  springProfilesActive: "gcp"
  # Deployment
  requestsCpu: "50m"
  requestsMemory: "350M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  # redis connection. Change it if you want to use external redis
  redisDatasetHost: ""
  redisDatasetPort: 6379
  redisImage: "redis:7"

conf:
  configmap: "dataset-config"
  postgresSecretName: "dataset-postgres-secret"
  appName: "dataset"
  onPremEnabled: false
  domain: ""
  datasetRedisSecretName: "dataset-redis-secret"

istio:
  proxyCPU: "25m"
  proxyCPULimit: "200m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "256Mi"
