{{ if not .Values.data.redisDatasetHost }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "redis-%s" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    type: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "redis-%s" .Values.conf.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "redis-%s" .Values.conf.appName | quote }}
      annotations:
        sidecar.istio.io/proxyCPU: 5m
        sidecar.istio.io/proxyMemory: 50Mi
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: {{ .Values.conf.datasetRedisSecretName | quote }}
        image: {{ .Values.data.redisImage | quote }}
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        name: {{ printf "redis-%s" .Values.conf.appName | quote }}
        args:
        - --requirepass
        - $(REDIS_PASSWORD)
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 20Mi
{{ end }}
