
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/testing"
    schedule:
      interval: "daily"
      time: "10:00"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"