
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/testing"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: "main"
    ignore:
     - dependency-name: "*"