
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/dataset-core-plus"
    schedule:
        interval: "daily"
        time: "09:00"
    target-branch: "main"
    allow:
        - dependency-type: "all"
    ignore:
        - dependency-name: "*"