variables:
  GC_SERVICE: dataset
  GC_VENDOR: gc

gc-test:
  variables:
    LEGAL_TAG: datatest-int-tag

gc-dev2-test:
  variables:
    LEGAL_TAG: datatest-int-tag

gc-baremetal-test:
  variables:
    LEGAL_TAG: public-usa-dataset-1
