variables:
  GC_SERVICE: dataset
  # FIXME remove when all services are migrated to a single helm
  GC_ENABLE_HELM_CONFIG: "false"
  GC_SERVICE: dataset
  GC_VENDOR: gc

gc-test:
  variables:
    LEGAL_TAG: datatest-int-tag

gc-dev2-test:
  variables:
    LEGAL_TAG: datatest-int-tag

gc-anthos-test:
  variables:
    LEGAL_TAG: public-usa-dataset-1
